image: node:latest

stages:
- test
- deploy

back_test:
  stage: test
  before_script:
    - cd back
  script:
    - yarn
    - yarn test

deploy:
  stage: deploy
  image: komly/ansible-playbook:latest
  script:
    - apt-get update -y && apt-get install -y rsync
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$KEY" | tr -d '\r' > ~/.ssh/key.rsa
    - chmod 600 ~/.ssh/key.rsa
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/key.rsa
    - ssh-keyscan -H $backendIp >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i .ansible/inventory .ansible/server.yml --extra-vars="serverPort=$serverPort dbHost=$dbHost dbPort=$dbPort dbUser=$dbUser dbPass=$dbPass dbName=$dbName backendIp=$backendIp backendPort=$backendPort"
  when: manual
  only:
    - master
