- hosts: server

  tasks:
    - name: deploy code
      synchronize:
        src: ../../
        dest: /app/mckinsey/
        times: no
        rsync_opts:
            - "--exclude=.git"
            - "--exclude=.ansible"
            - "--exclude=node_modules/*"
    - name: yarn front
      shell: yarn
      args:
        chdir: /app/mckinsey/front
    - name: yarn back
      shell: yarn
      args:
        chdir: /app/mckinsey/back
    - name: enable create dotenv files
      shell:
        cmd: |
               cat > /app/mckinsey/back/.env <<EOF
               serverPort={{ serverPort }}
               dbHost={{ dbHost }}
               dbPort={{ dbPort }}
               dbUser={{ dbUser }}
               dbPass={{ dbPass }}
               dbName={{ dbName }}
               EOF
    - name: migrate
      shell: node migrate.js
      args:
        chdir: /app/mckinsey/back
    - name: stop back
      command: pm2 stop mc-back
      become: true
      ignore_errors: yes
    - name: run back
      command: pm2 start node main.js --name mc-back
      args:
        chdir: /app/mckinsey/back
    - name: stop front
      command: pm2 stop mc-front
      become: true
      ignore_errors: yes
    - name: run front
      command: pm2 start node_modules/react-scripts/bin/react-scripts.js --name mc-front -- start
      args:
        chdir: /app/mckinsey/front
