- hosts: server

  tasks:
    - name: deploy code
      synchronize:
        src: ../../
        dest: /app/mckinsey/
        times: no
        rsync_opts:
            - "--exclude=.git"
            - "--exclude=.ansible"
            - "--exclude=node_modules/*"
        become: yes

    - name: yarn front
      shell: yarn
      args:
        chdir: /app/mckinsey/front
      become: yes

    - name: yarn back
      shell: yarn
      args:
        chdir: /app/mckinsey/back
      become: yes

    - name: create back dotenv files
      shell:
        cmd: |
               cat > /app/mckinsey/back/.env <<EOF
               serverPort={{ serverPort }}
               dbHost={{ dbHost }}
               dbPort={{ dbPort }}
               dbUser={{ dbUser }}
               dbPass={{ dbPass }}
               dbName={{ dbName }}
               EOF

    - name: create front dotenv files
      shell:
        cmd: |
           cat > /app/mckinsey/front/.env <<EOF
           REACT_APP_BACKEND_IP={{ backendIp }}
           REACT_APP_BACKEND_PORT={{ backendPort }}
           EOF

    - name: migrate
      shell: node migrate.js
      args:
        chdir: /app/mckinsey/back

    - name: stop back
      command: pm2 delete mc-back
      ignore_errors: yes

    - name: run back
      command: pm2 start node main.js --name mc-back
      args:
        chdir: /app/mckinsey/back

    - name: stop front
      command: pm2 delete mc-front
      ignore_errors: yes

    - name: run front
      command: pm2 start yarn --name mc-front -- start
      args:
        chdir: /app/mckinsey/front
