DROP TABLE IF EXISTS content CASCADE;
CREATE TABLE content (
   id SERIAL PRIMARY KEY,
   title VARCHAR(256) NOT NULL,
   is_visible BOOLEAN NOT NULL DEFAULT TRUE,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS "user" CASCADE;
CREATE TABLE "user" (
  id SERIAL PRIMARY KEY,
  login VARCHAR(256) NOT NULL,
  password VARCHAR(256) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(login)
);

DROP TABLE IF EXISTS type CASCADE;
CREATE TABLE type (
   id SERIAL PRIMARY KEY,
   title VARCHAR(256) NOT NULL
);

DROP TABLE IF EXISTS state CASCADE;
CREATE TABLE state (
   id SERIAL PRIMARY KEY,
   title VARCHAR(256) NOT NULL
);

DROP TABLE IF EXISTS report CASCADE;
CREATE TABLE report (
   id SERIAL PRIMARY KEY,
   state INT REFERENCES state(id),
   type INT REFERENCES type(id) ON DELETE CASCADE ON UPDATE CASCADE,
   message TEXT,
   fk_content INT REFERENCES content(id) ON DELETE CASCADE ON UPDATE CASCADE,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   fk_user INT REFERENCES "user"(id) ON DELETE SET NULL ON UPDATE CASCADE
);
